In [ ]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import balanced_accuracy_score, precision_recall_fscore_support
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.metrics import precision_score, recall_score, f1_score


##XGBoost Grid Search with features other than course data

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold

In [ ]:
params = {
        'learning_rate':[0.1,0.01,0.001,0.005],
        'min_child_weight': [1, 5, 10],
        'gamma': [0.5, 1, 1.5, 2, 5],
        'subsample': [0.6, 0.8, 1.0],
        'colsample_bytree': [0.6, 0.8, 1.0]         
        }

In [ ]:
cv=RepeatedStratifiedKFold(n_splits=2,n_repeats=1)

In [ ]:
xgbgs = xgb.XGBClassifier(n_estimators=100)
                      # , objective='binary:logistic',
                    # silent=True, nthread=1)

In [ ]:
grid = GridSearchCV(estimator=xgbgs, param_grid=params, scoring='precision', n_jobs=-1, cv=cv, verbose=1 )

In [ ]:
grid.fit(X_train,y_train)

Fitting 2 folds for each of 540 candidates, totalling 1080 fits


GridSearchCV(cv=RepeatedStratifiedKFold(n_repeats=1, n_splits=2, random_state=None),
             estimator=XGBClassifier(), n_jobs=-1,
             param_grid={'colsample_bytree': [0.6, 0.8, 1.0],
                         'gamma': [0.5, 1, 1.5, 2, 5],
                         'learning_rate': [0.1, 0.01, 0.001, 0.005],
                         'min_child_weight': [1, 5, 10],
                         'subsample': [0.6, 0.8, 1.0]},
             scoring='precision', verbose=1)

In [ ]:
results=pd.DataFrame(grid.cv_results_)
results

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         8.608196      0.069450         0.079913        0.003844   
1         7.514906      0.062437         0.081028        0.002368   
2         6.953359      0.011724         0.094065        0.005662   
3         8.329368      0.015628         0.086037        0.005685   
4         7.511575      0.023605         0.083516        0.004721   
..             ...           ...              ...             ...   
535      12.005625      0.082091         0.072457        0.001447   
536       8.955644      0.086556         0.075272        0.002666   
537      12.231062      0.035023         0.075766        0.002953   
538      10.794033      0.040032         0.071156        0.000542   
539       8.518864      0.349461         0.061741        0.013541   

    param_colsample_bytree param_gamma param_learning_rate  \
0                      0.6         0.5                 0.1   
1                      0.6         0.5                 0.1   
2                      0.6         0.5                 0.1   
3                      0.6         0.5                 0.1   
4                      0.6         0.5                 0.1   
..                     ...         ...                 ...   
535                    1.0           5               0.005   
536                    1.0           5               0.005   
537                    1.0           5               0.005   
538                    1.0           5               0.005   
539                    1.0           5               0.005   

    param_min_child_weight param_subsample  \
0                        1             0.6   
1                        1             0.8   
2                        1             1.0   
3                        5             0.6   
4                        5             0.8   
..                     ...             ...   
535                      5             0.8   
536                      5             1.0   
537                     10             0.6   
538                     10             0.8   
539                     10             1.0   

                                                params  split0_test_score  \
0    {'colsample_bytree': 0.6, 'gamma': 0.5, 'learn...           0.926876   
1    {'colsample_bytree': 0.6, 'gamma': 0.5, 'learn...           0.927221   
2    {'colsample_bytree': 0.6, 'gamma': 0.5, 'learn...           0.931992   
3    {'colsample_bytree': 0.6, 'gamma': 0.5, 'learn...           0.923295   
4    {'colsample_bytree': 0.6, 'gamma': 0.5, 'learn...           0.922787   
..                                                 ...                ...   
535  {'colsample_bytree': 1.0, 'gamma': 5, 'learnin...           0.930799   
536  {'colsample_bytree': 1.0, 'gamma': 5, 'learnin...           0.930664   
537  {'colsample_bytree': 1.0, 'gamma': 5, 'learnin...           0.928225   
538  {'colsample_bytree': 1.0, 'gamma': 5, 'learnin...           0.928086   
539  {'colsample_bytree': 1.0, 'gamma': 5, 'learnin...           0.930664   

     split1_test_score  mean_test_score  std_test_score  rank_test_score  
0             0.919400         0.923138        0.003738              424  
1             0.922285         0.924753        0.002468              373  
2             0.925401         0.928697        0.003296              177  
3             0.921846         0.922571        0.000725              431  
4             0.922495         0.922641        0.000146              430  
..                 ...              ...             ...              ...  
535           0.927593         0.929196        0.001603               95  
536           0.927664         0.929164        0.001500              105  
537           0.921965         0.925095        0.003130              357  
538           0.927593         0.927839        0.000246              231  
539           0.927664         0.929164        0.001500              105  

[540 rows x 15 columns]

In [ ]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   mean_fit_time           540 non-null    float64
 1   std_fit_time            540 non-null    float64
 2   mean_score_time         540 non-null    float64
 3   std_score_time          540 non-null    float64
 4   param_colsample_bytree  540 non-null    object 
 5   param_gamma             540 non-null    object 
 6   param_learning_rate     540 non-null    object 
 7   param_min_child_weight  540 non-null    object 
 8   param_subsample         540 non-null    object 
 9   params                  540 non-null    object 
 10  split0_test_score       540 non-null    float64
 11  split1_test_score       540 non-null    float64
 12  mean_test_score         540 non-null    float64
 13  std_test_score          540 non-null    float64
 14  rank_test_score         540 non-null    in

In [ ]:
results.to_csv('grid-xgboost-results.csv')

In [ ]:
y_pred=grid.best_estimator_.predict(X_test)

In [ ]:
y_prob=grid.best_estimator_.predict_proba(X_test)

In [ ]:
y_testprob = grid.best_estimator_.predict_proba(test)
results_df = pd.DataFrame(data={'id':test_df['id'], 'target':y_test[:,1]})
results_df.to_csv('submission-grid-search-xgb-porto-01.csv', index=False)

In [ ]:
grid.best_estimator_

XGBClassifier(colsample_bytree=1.0, gamma=0.5, learning_rate=0.001,
              subsample=1.0)

In [ ]:
grid.best_params_

{'colsample_bytree': 1.0,
 'gamma': 0.5,
 'learning_rate': 0.001,
 'min_child_weight': 1,
 'subsample': 1.0}

In [ ]:
confusion_matrix(y_pred,y_test)

array([[6556,  121],
       [  45,  506]])

In [ ]:
precision_recall_fscore_support(y_pred,y_test)

(array([0.99318285, 0.80701754]),
 array([0.98187809, 0.91833031]),
 array([0.98749812, 0.85908319]),
 array([6677,  551]))

##Grid Search for Tensorflow - All Features

In [ ]:
import tensorflow as tf

In [ ]:
data=pd.read_csv('df_student_features_entiredata.csv')

In [ ]:
data.drop(columns=['Unnamed: 0','subscriptiontype','onboard_flag'],inplace=True)

In [ ]:
data.info()

In [ ]:
from sklearn.preprocessing import label_binarize

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.compose import make_column_transformer, make_column_selector

In [ ]:
data['conversion'].value_counts()

0    33095
1     3041
Name: conversion, dtype: int64

In [ ]:
y=data['conversion']
X=data.drop(columns=['conversion'])

In [ ]:
ct1=make_column_transformer(
    (OneHotEncoder(sparse=False),make_column_selector(dtype_include=object)),
(StandardScaler(),make_column_selector(dtype_exclude=object)))


In [ ]:
X=ct1.fit_transform(X)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,shuffle=True)

In [ ]:
!pip install scikeras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from scikeras.wrappers import KerasClassifier

In [ ]:
X_train.shape[-1]

241

In [ ]:
def create_model(neuron1,neuron2,neuron3):
  model = tf.keras.models.Sequential()
  model.add(tf.keras.layers.Dense(neuron1, input_shape=(241,), activation='relu'))
  model.add(tf.keras.layers.Dense(neuron2, activation='relu'))
  model.add(tf.keras.layers.Dense(neuron3, activation='relu'))
  model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model

In [ ]:
model_grid=KerasClassifier(model=create_model,epochs=50,batch_size=32)

In [ ]:
neuron1=[10,30,40]
neuron2=[10,20,30,]
neuron3=[10,20]

# learning_rate=[0.3,0.2,0.1,0.01,0.05,0.001,0.005]
# momentum = [0.0, 0.2, 0.4, 0.6, 0.8, 0.9]
# optimizer = ['RMSprop', 'Adagrad', 'Adadelta', 'Adam','Nadam']
# lamd=[0.3,0.2,0.1,0.01,0.05,0.001,0.005]
# param_grid = dict(model__neuron1=neuron1,model__neuron2=neuron2,model__neuron3=neuron3, model__lamd=lamd,
#                   optimizer__learning_rate=learning_rate, optimizer=optimizer)

param_grid = dict(model__neuron1=neuron1,model__neuron2=neuron2,model__neuron3=neuron3)
                  # , model__lamd=lamd)

In [ ]:
from scikeras.wrappers import KerasClassifier

In [ ]:
grid=GridSearchCV(estimator=model_grid, param_grid=param_grid,n_jobs=-1,cv=3,scoring='precision')

In [ ]:
grid_results=grid.fit(X_train,y_train)
                      # ,validation_data=(X_test,y_test),
                      # callbacks=[early_stop],verbose=1)

/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py:703: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning


Epoch 1/50
904/904 [==============================] - 2s 2ms/step - loss: 0.1260 - accuracy: 0.9619
Epoch 2/50
904/904 [==============================] - 2s 2ms/step - loss: 0.0829 - accuracy: 0.9740
Epoch 3/50
904/904 [==============================] - 2s 2ms/step - loss: 0.0746 - accuracy: 0.9766
Epoch 4/50
904/904 [==============================] - 2s 2ms/step - loss: 0.0693 - accuracy: 0.9788
Epoch 5/50
904/904 [==============================] - 2s 2ms/step - loss: 0.0658 - accuracy: 0.9796
Epoch 6/50
904/904 [==============================] - 2s 2ms/step - loss: 0.0627 - accuracy: 0.9807
Epoch 7/50
904/904 [==============================] - 2s 2ms/step - loss: 0.0596 - accuracy: 0.9818
Epoch 8/50
904/904 [==============================] - 2s 2ms/step - loss: 0.0577 - accuracy: 0.9825
Epoch 9/50
904/904 [==============================] - 2s 2ms/step - loss: 0.0552 - accuracy: 0.9829
Epoch 10/50
904/904 [==============================] - 2s 2ms/step - loss: 0.0544 - accuracy: 0.9832

In [ ]:
results=pd.DataFrame(grid_results.cv_results_)
results

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0      122.429649     29.001766         0.972288        0.341137   
1       82.744449      0.185426         1.027040        0.416979   
2       76.786206      5.780363         1.222218        0.270169   
3       75.803257      5.654598         1.199817        0.290164   
4      103.116301     28.151839         0.676200        0.139198   
5      102.853053     28.412576         0.982967        0.317790   
6       92.476822     37.889367         0.627369        0.120544   
7      100.754773     29.820171         0.997051        0.291657   
8       70.315531     14.725329         0.560405        0.132644   
9      102.867966     28.322742         1.207745        0.291649   
10      73.175357     13.507115         0.657677        0.150241   
11      95.330169     35.072285         1.197235        0.349972   
12      77.535780      5.764741         1.193096        0.304838   
13      78.059877      6.782944         0.748586        0.007634   
14      82.330373      0.968417         1.669811        0.871295   
15      80.050980      2.128062         0.923240        0.343963   
16     102.945006     28.344595         0.979318        0.297581   
17      74.567593     11.564169         0.769213        0.049251   

   param_model__neuron1 param_model__neuron2 param_model__neuron3  \
0                    10                   10                   10   
1                    10                   10                   20   
2                    10                   20                   10   
3                    10                   20                   20   
4                    10                   30                   10   
5                    10                   30                   20   
6                    30                   10                   10   
7                    30                   10                   20   
8                    30                   20                   10   
9                    30                   20                   20   
10                   30                   30                   10   
11                   30                   30                   20   
12                   40                   10                   10   
13                   40                   10                   20   
14                   40                   20                   10   
15                   40                   20                   20   
16                   40                   30                   10   
17                   40                   30                   20   

                                               params  split0_test_score  \
0   {'model__neuron1': 10, 'model__neuron2': 10, '...           0.975301   
1   {'model__neuron1': 10, 'model__neuron2': 10, '...           0.975509   
2   {'model__neuron1': 10, 'model__neuron2': 20, '...           0.975612   
3   {'model__neuron1': 10, 'model__neuron2': 20, '...           0.974056   
4   {'model__neuron1': 10, 'model__neuron2': 30, '...           0.976339   
5   {'model__neuron1': 10, 'model__neuron2': 30, '...           0.976443   
6   {'model__neuron1': 30, 'model__neuron2': 10, '...           0.976235   
7   {'model__neuron1': 30, 'model__neuron2': 10, '...           0.974575   
8   {'model__neuron1': 30, 'model__neuron2': 20, '...           0.975820   
9   {'model__neuron1': 30, 'model__neuron2': 20, '...           0.976754   
10  {'model__neuron1': 30, 'model__neuron2': 30, '...           0.977480   
11  {'model__neuron1': 30, 'model__neuron2': 30, '...           0.976235   
12  {'model__neuron1': 40, 'model__neuron2': 10, '...           0.975197   
13  {'model__neuron1': 40, 'model__neuron2': 10, '...           0.974056   
14  {'model__neuron1': 40, 'model__neuron2': 20, '...           0.975197   
15  {'model__neuron1': 40, 'model__neuron2': 20, '...           0.977273   
16  {'model__neuron1': 40, 'model__neuron2': 30, '...           0.975405   
17  {'model__neuron1': 40, 'mod

In [ ]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   mean_fit_time         18 non-null     float64
 1   std_fit_time          18 non-null     float64
 2   mean_score_time       18 non-null     float64
 3   std_score_time        18 non-null     float64
 4   param_model__neuron1  18 non-null     object 
 5   param_model__neuron2  18 non-null     object 
 6   param_model__neuron3  18 non-null     object 
 7   params                18 non-null     object 
 8   split0_test_score     18 non-null     float64
 9   split1_test_score     18 non-null     float64
 10  split2_test_score     18 non-null     float64
 11  mean_test_score       18 non-null     float64
 12  std_test_score        18 non-null     float64
 13  rank_test_score       18 non-null     int32  
dtypes: float64(9), int32(1), object(4)
memory usage: 2.0+ KB


In [ ]:
results.to_csv('grid-deeplearning-results.csv')

In [ ]:
y_pred=grid_results.best_estimator_.predict(X_test)

226/226 [==============================] - 0s 1ms/step


In [ ]:
y_pred=tf.round(grid_results.best_estimator_.predict(X_test))

226/226 [==============================] - 0s 2ms/step


In [ ]:
y_prob=grid_results.best_estimator_.predict_proba(X_test)

226/226 [==============================] - 0s 1ms/step


In [ ]:
grid_results.best_estimator_

KerasClassifier(
	model=<function create_model at 0x7f5a31317dd0>
	build_fn=None
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=32
	validation_batch_size=None
	verbose=1
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=50
	model__neuron1=30
	model__neuron2=20
	model__neuron3=20
	class_weight=None
)

In [ ]:
grid_results.best_params_

{'model__neuron1': 30, 'model__neuron2': 20, 'model__neuron3': 20}

In [ ]:
confusion_matrix(tf.round(y_pred),y_test)

array([[6571,  129],
       [  42,  486]])

In [ ]:
precision_recall_fscore_support(tf.round(y_pred),y_test)

(array([0.99364887, 0.7902439 ]),
 array([0.98074627, 0.92045455]),
 array([0.98715541, 0.8503937 ]),
 array([6700,  528]))